### ISSUE TITLE
NP++64bit Major Crash when NppQcp Color Highlight Active

### ISSUE THREAD

**Issue by SevenFactors** [JetNpp/NppQcp#1]
When NppQcp color highlight is active, N++ crashes instantly. The crash also resets part of N++ theme (user-set  theme). 

**The scenario:** 
- Notepad++ 64bit ver 8.5.2 - NppQcp ver 2.0.0
- I have N++ with a dark theme set. I open a .css file for editing OR just launch N++ to keep working on a .css file and N++ instantly crashes. 
- When opening N++ after the crash, will have N++ reset back to its formal light theme.

**Remedy**
When NppQcp color highlight  is turned off, the issue is non existent. The moment color highlight is turned on, N++ hard crashes.

 I installed NppQcp 64bit plugin manually, given that is is not present on the N++ plugin admin repository.

It would be great to have NppQcp features working properly on N++ 64bit.
Please fix. I don't know if this issue is the cause NppQcp hasn't been present/natively shown on N++ plugings manager repo. I find this plugins to be essential to the point that it should be built into N++

I hope this helps some how.

Thanks you for your work/this plugin.

**Comment by JetMeta** [comment]
I fixed in my env and have pushed. You can try it, hope help.

btw, work under Mac several years and have a hard full-time job, so little time to maintain those plugins. may sometimes recompile them, can not be guaranteed.

**Comment by SevenFactors** [comment]
Thank you very much for taking the time out of your schedule to fix the issue in such short time.

The reported issue is no longer present. It has been fixed. I've been using N++ with NppQcp 2.0.0.1 without any problem.

 You even fixed a behavior where one had to press ESC to close the color palette but now a simple click anywhere outside of the palette exits the color palette. 


<img width="454" alt="nppqcp_underliness" src="https://user-images.githubusercontent.com/6032777/235318633-e9e7ab18-ff0f-4b2e-84dc-a93db1b0a1e5.png">
